---
name: "Auto-doc shell scripts"

on: [push, pull_request, workflow_dispatch]

jobs:
  shdoc:
    name: "shdoc"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Documentation generator"
        uses: a5k-testing/shell-doc-action-test@main
      - name: "aaa"
        shell: bash
        run: |
          # Compiling shdoc...
          action_path="${{ github.action_path }}"
          ls "${action_path}/docs/"
